// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWork.Db;

namespace TestWork.Db.Migrations
{
    [DbContext(typeof(TestWorkDbContext))]
    partial class TestWorkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWork.Db.Models.EmployeeGroupModel", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("СотрудникиГруппы");
                });

            modelBuilder.Entity("TestWork.Db.Models.EmployeeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Сотрудники");
                });

            modelBuilder.Entity("TestWork.Db.Models.GroupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Группы");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6072d11-1643-4003-87e9-d09547db8b2c"),
                            CreatedAtUtc = new DateTime(2022, 11, 13, 14, 8, 12, 446, DateTimeKind.Utc).AddTicks(9667),
                            Name = "Администраторы"
                        },
                        new
                        {
                            Id = new Guid("b2f1195a-00d3-4f68-a1a4-472ee50ebd72"),
                            CreatedAtUtc = new DateTime(2022, 11, 13, 14, 8, 12, 447, DateTimeKind.Utc).AddTicks(212),
                            Name = "Руководство"
                        });
                });

            modelBuilder.Entity("TestWork.Db.Models.EmployeeGroupModel", b =>
                {
                    b.HasOne("TestWork.Db.Models.EmployeeModel", "Employee")
                        .WithMany("Groups")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestWork.Db.Models.GroupModel", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TestWork.Db.Models.EmployeeModel", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
